### ISSUE TITLE
THIS IS A VIRUS

### ISSUE THREAD

**Issue by JABSOL** [Jesewe/PCPerfomanceBoost#1]
VIRUS TOTAL LINK: https://www.virustotal.com/gui/file/b83da7806df497844b5edb9dfd074b5a7dcfb833cd508907a3322e032e81c870/detection

**Comment by Jesewe** [comment]
**Viruses are detected by nouname (unknown's) antiviruses, since C# uses system modules.** 
You can download the source code of the project, and Build Solution.

**Comment by Jesewe** [comment]
The release (v1.0.0.4) has been updated
